### ISSUE TITLE
The problem of multi-die FPGA  design partitioning problem

### ISSUE THREAD

**Issue by fzwwj95** [PKU-IDEA/OpenPARF#10]
Does OpenPARF 2.0 perform partitioning for the designs of multi-die FPGA? 
Does the circuit netlist input into OpenPARF 2.0 already undergone operations related to partitioning?

**Comment by RunzheTao** [comment]
Thanks for your questions about OpenPARF 2.0!
Currently, OpenPARF 2.0 doesn't include an explicit partitioning step. While partition-place methods were used in some previous multi-die placers to minimize SLL counts, this approach tends to constrain the solution space too early without considering actual device resources and constraints.
Instead, OpenPARF 2.0 lets the entire placement solution naturally converge and distribute across multiple SLRs (like vertically distributed dies) based on the specified objectives and constraints. We believe this more holistic approach leads to better overall placement results.
Let me know if you have any other questions.

**Comment by fzwwj95** [comment]
Thanks for answering.
