### ISSUE TITLE
Question about the routing

### ISSUE THREAD

**Issue by HeadRaising123** [PKU-IDEA/OpenPARF#4]
Thank you very much for your open-source framework！Hello author, when I installed OpenPARF, the placement was able to run, but when using the router provided by the author, I found that router could not be done. After investigating the reason, I found that in line 22 of/OpenPARF/openparf/routing/router. py, import router_ cpp, it is not possible to parse the import "router_cpp". I couldn't find this package in the Python environment.  Could you tell me where the problem is and then how to solve it?Thank you!
![Question for the routing](https://github.com/PKU-IDEA/OpenPARF/assets/131114508/ab6da914-94d3-42cb-8957-9f28da0d8b53)

**Comment by magic3007** [comment]
Thank you very much for your interest in OpenPARF. May I inquire if you have set the `ENABLE_ROUTER` option to disable when running the cmake command?

<img width="713" alt="image" src="https://github.com/PKU-IDEA/OpenPARF/assets/30785720/fc098d5a-793d-4a5e-b29e-3071e9c55d97">

It would be better for debugging if you could provide a complete screenshot of the running command.

**Comment by JustinJustinJustinJustinJustin666** [comment]
作者你好，非常感谢你们的开源布局布线框架！我也遇到了上述问题，即已经将```ENABLE_ROUTER```设置为```ON```了，也无法进行布线，输出No error，Segmentation fault (core dumped)。于是我重新安装了一遍OpenPARF，在cmake阶段遇到了如下问题。
![1705996655360](https://github.com/PKU-IDEA/OpenPARF/assets/145088981/6ae57727-fec2-4e36-8569-5607d99bbc96)
![image](https://github.com/PKU-IDEA/OpenPARF/assets/145088981/a0082b8a-4e89-42ba-b8c2-0d57e893fd05)
这是我的cmake指令
```
cmake .. -DCMAKE_PREFIX_PATH=/home/gdut/anaconda3/envs/openparf -DPYTHON_EXECUTABLE=/home/gdut/anaconda3/envs/openparf/bin/python -DPython3_EXECUTABLE=/home/gdut/anaconda3/envs/openparf/bin/python -DCMAKE_INSTALL_PREFIX=/home/gdut/OpenPARF/install
```

**Comment by magic3007** [comment]
If `ENABLE_ROUTER` has already been set to ON, the appropriate make command should be 
```
cmake .. -DCMAKE_PREFIX_PATH=/home/gdut/anaconda3/envs/openparf -DPYTHON_EXECUTABLE=/home/gdut/anaconda3/envs/openparf/bin/python -DPython3_EXECUTABLE=/home/gdut/anaconda3/envs/openparf/bin/python -DCMAKE_INSTALL_PREFIX=/home/gdut/OpenPARF/install -DENABLE_ROUTER=1
```
Please try using this command.

**Comment by JustinJustinJustinJustinJustin666** [comment]
> If `ENABLE_ROUTER` has already been set to ON, the appropriate make command should be
> 
> ```
> cmake .. -DCMAKE_PREFIX_PATH=/home/gdut/anaconda3/envs/openparf -DPYTHON_EXECUTABLE=/home/gdut/anaconda3/envs/openparf/bin/python -DPython3_EXECUTABLE=/home/gdut/anaconda3/envs/openparf/bin/python -DCMAKE_INSTALL_PREFIX=/home/gdut/OpenPARF/install -DENABLE_ROUTER=1
> ```
> 
> Please try using this command.

作者你好，我使用了你所提供的cmake指令进行cmake，make，make install。以ISPD2016的benchmark为例，在FPGA01.json中，添加了`"route_flag" : 1,`。由于没有GPU，我将GPU选项设置为`"gpu" : 0,`。随后我在install的文件夹中执行该命令
```
python openparf.py --config unittest/regression/ispd2016/FPGA01.json 
``` 
最后输出的反馈如图所示。
![image](https://github.com/PKU-IDEA/OpenPARF/assets/145088981/d57d445c-0b99-4c6b-b1e4-1b4175996846)

**Comment by magic3007** [comment]
I'm very sorry, the compilation option should be set to `-DENABLE_ROUTER=ON`.
Please use the following cmake command:
```
cmake .. -DCMAKE_PREFIX_PATH=/home/gdut/anaconda3/envs/openparf -DPYTHON_EXECUTABLE=/home/gdut/anaconda3/envs/openparf/bin/python -DPython3_EXECUTABLE=/home/gdut/anaconda3/envs/openparf/bin/python -DCMAKE_INSTALL_PREFIX=/home/gdut/OpenPARF/install -DENABLE_ROUTER=ON
```

**Comment by JustinJustinJustinJustinJustin666** [comment]
作者你好，我使用了你提供的cmake指令进行cmake，make，make install。依然是以ISPD2016的benchmark为例，在FPGA01.json中，添加了"route_flag" : 1,。由于没有GPU，我将GPU选项设置为"gpu" : 0,。随后我在install的文件夹中执行命令
```
python openparf.py --config unittest/regression/ispd2016/FPGA01.json 
```
之后，出现了`Segmentation fault (core dumped)`的情况
![image](https://github.com/PKU-IDEA/OpenPARF/assets/145088981/53b7002c-d5be-49af-9b16-6bb586759706)

**Comment by magic3007** [comment]
Please confirm the following:

1. The version of G++ is 7.5.0. In our previous trials, errors have occurred when other versions were used.
2. Ensure that [the XML file](https://github.com/PKU-IDEA/OpenPARF/blob/master/openparf/routing/fpga-router/archs/x_arch.xml) is accessible and readable.

**Comment by magic3007** [comment]
We are fixing issues with the compiler, to make the program work in other compilation environments as well.

**Comment by JustinJustinJustinJustinJustin666** [comment]
> Please confirm the following:
> 
> 1. The version of G++ is 7.5.0. In our previous trials, errors have occurred when other versions were used.
> 2. Ensure that [the XML file](https://github.com/PKU-IDEA/OpenPARF/blob/master/openparf/routing/fpga-router/archs/x_arch.xml) is accessible and readable.

G++版本为7.5.0，XML文件也是可访问可读的。
依然是以ISPD2016的benchmark为例，在FPGA01.json中，添加了"route_flag" : 1,。由于没有GPU，我将GPU选项设置为"gpu" : 0,。
执行该命令:
```
python openparf.py --config unittest/regression/ispd2016/FPGA01.json
 ```
输出以下结果
![image](https://github.com/PKU-IDEA/OpenPARF/assets/145088981/33ce0354-ff98-432f-b0f3-0d18a8d18634)

**Comment by magic3007** [comment]
Greetings,

To enhance our comprehension and replication of the quandary you are encountering, could you kindly furnish additional particulars pertaining to your environment? In particular, the following information would be instrumental:

1. The operating system employed, inclusive of its version.
2. The iteration of the pertinent software or library, for instance, Python, Torch, g++, etc.
3. Any dependent software and their corresponding versions.
4. A detailed sequence of actions that precipitated the issue.
5. In the event the issue arises within a Docker container, it would be greatly beneficial if you could supply the Docker image or the Dockerfile utilized to establish the environment. This will enable us to precisely emulate your setup and scrutinize the issue under identical conditions.

Such information will significantly aid in diagnosing and rectifying the predicament.

**Comment by magic3007** [comment]
Hi,
could you please send us the results of the placement, i.e., `results/FPGA01/FPGA01.pl` for debugging? (My email address is jingmai at pku dot edu dot cn).

**Comment by magic3007** [comment]
> > Please confirm the following:
> > 
> > 1. The version of G++ is 7.5.0. In our previous trials, errors have occurred when other versions were used.
> > 2. Ensure that [the XML file](https://github.com/PKU-IDEA/OpenPARF/blob/master/openparf/routing/fpga-router/archs/x_arch.xml) is accessible and readable.
> 
> G++版本为7.5.0，XML文件也是可访问可读的。 依然是以ISPD2016的benchmark为例，在FPGA01.json中，添加了"route_flag" : 1,。由于没有GPU，我将GPU选项设置为"gpu" : 0,。 执行该命令:
> 
> ```
> python openparf.py --config unittest/regression/ispd2016/FPGA01.json
> ```
> 
> 输出以下结果 ![image](https://private-user-images.githubusercontent.com/145088981/308041392-33ce0354-ff98-432f-b0f3-0d18a8d18634.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxODYzMTYsIm5iZiI6MTcwOTE4NjAxNiwicGF0aCI6Ii8xNDUwODg5ODEvMzA4MDQxMzkyLTMzY2UwMzU0LWZmOTgtNDMyZi1iMGYzLTBkMThhOGQxODYzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOVQwNTUzMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2UxOTJjOWY1MGI4ODViMjU3NmFkMjgwMGRkNTg5NjM5YmYwYjZkYjNhMjE4ZWI1ZjQ3N2NiMDQzYWMwZWJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-UIUPenBQFDKsafwhnVnRvmyfzyIjH_kPt-z4P5OudY)

Can you test it in an environment where both **gcc** and **g++** are version 7.5? I remember seeing that the version of gcc was not 7.5 before.
