### ISSUE TITLE
关于OpenPARF的安装问题

### ISSUE THREAD

**Issue by JustinJustinJustinJustinJustin666** [PKU-IDEA/OpenPARF#6]
作者你好，我将本地的OpenPARF使用```rm -rf OpenPARF```指令删除后，重新将OpenPARF克隆下来。我确保我的依赖及先决条件都与README中的一样。在进行cmake的时候会出现以下情况，
![image](https://github.com/PKU-IDEA/OpenPARF/assets/145088981/a08d2156-b68d-447a-bb38-320c6063de24)
在make的时候会出现以下情况，
![image](https://github.com/PKU-IDEA/OpenPARF/assets/145088981/1b23bd5a-0369-4733-91c1-8915a8a3e1f8)
在make install的时候会出现以下情况，
![image](https://github.com/PKU-IDEA/OpenPARF/assets/145088981/0290c922-ac3a-4d5e-b21d-777af508b68f)
请告诉我该怎么做？

**Comment by limbo018** [comment]
看起来是database编译报错。你把make -j 那一句改成 make，看一下单线程编译会报什么错？Yibo LinAssistant ProfessorPeking University On Feb 26, 2024, at 10:13 PM, JustinJustinJustinJustinJustin666 ***@***.***> wrote:﻿
作者你好，我将本地的OpenPARF使用rm -rf OpenPARF指令删除后，重新将OpenPARF克隆下来。我确保我的依赖及先决条件都与README中的一样。在进行cmake的时候会出现以下情况，
image.png (view on web)
在make的时候会出现以下情况，
image.png (view on web)
在make install的时候会出现以下情况，
image.png (view on web)
请告诉我该怎么做？

**Comment by magic3007** [comment]
I have added a [commit](https://github.com/PKU-IDEA/OpenPARF/commit/367fec828057dc4b6a4069f12a4a200de81b5a0c) to fix this bug on the master branch, please pull this commit.  

Additionally, could you please tell me your compiler and its version? This bug seems to have not thrown an error on our previous compiler.  Informing us could help us continue to improve. :)

**Comment by JustinJustinJustinJustinJustin666** [comment]
感谢二位及时的回复！OpenPARF安装成功了。
我的G++版本为7.5.0，GCC版本为7.5.0
![image](https://github.com/PKU-IDEA/OpenPARF/assets/145088981/5ecb0d57-b440-439f-b92e-285efbe5acc5)
![image](https://github.com/PKU-IDEA/OpenPARF/assets/145088981/014d667a-e928-47bf-a654-0143c068f2b4)
python版本为3.7.16

**Comment by magic3007** [comment]
According to the screenshot here, the gcc version is 9.4. Is there an issue with the router when running here?

**Comment by JustinJustinJustinJustinJustin666** [comment]
不好意思！在截屏的环境下无法布线，我刚刚在cmake日志中检查发现C++的编译器使用的是clang10.0.0版本，当我换了G++7.5.0之后并清除构建目录重新进行cmake、make、make install后，可以成功进行布线！
感谢作者！
