### ISSUE TITLE
Git clone issue missing benchmark

### ISSUE THREAD

**Issue by zhilix** [PKU-IDEA/OpenPARF#7]
When I was trying to run "git clone --recursive https://github.com/PKU-IDEA/OpenPARF.git"

It ran into an error:
> Downloading benchmarks/sample1/design.pl (110 B)
> Error downloading object: benchmarks/sample1/design.pl (b8b753b): Smudge error: Error downloading benchmarks/sample1/design.pl (b8b753bcee2ca1a55fd2af9ed1af75b718028cc929a922d4a6646f91036feb3c): [b8b753bcee2ca1a55fd2af9ed1af75b718028cc929a922d4a6646f91036feb3c] Object does not exist on the server: [404] Object does not exist on the server
> 
> Errors logged to /home/local/eda15/zhilix/projects/OpenPARF/.git/lfs/logs/20240226T100409.759435645.log

Thus git clone terminated early and I was not able to build.

**Comment by magic3007** [comment]
Hi Zhili,

I suspect this might be a lingering issue with Git LFS. Try disabling Git LFS on your server using the following command:

```
GIT_LFS_SKIP_SMUDGE=1 git clone --recursive https://github.com/PKU-IDEA/OpenPARF.git
```

Let me know if this helps!

**Comment by zhilix** [comment]
Thank you! with "GIT_LFS_SKIP_SMUDGE=1", I can finish git clone and building is also successful.
