### ISSUE TITLE
Question about Vivado Flow for Placement Evaluation

### ISSUE THREAD

**Issue by JustinJustinJustinJustinJustin666** [PKU-IDEA/OpenPARF#8]
I have downloaded Vivado2015.4 on my Linux server. According to the instructions on the official websites for ISPD, I try to load the placement results into the Vivado flow. I use this command to run Vivado flow.
This is my Vivado installation package.```Xilinx_Vivado_SDK_Lin_2015.4_1118_2.tar.gz```
```
/opt/Xilinx/Vivado/2015.4/bin/vivado -mode batch -source ~/flow.tcl
```
the terminal output shows
![image](https://github.com/PKU-IDEA/OpenPARF/assets/145088981/95d5dbb9-84eb-4045-99f9-8379d987932c)
![image](https://github.com/PKU-IDEA/OpenPARF/assets/145088981/632fa0eb-ce26-4f4f-8560-42a9141a1b4f)
Please tell me how to solve it.
Thanks a lot!

**Comment by magic3007** [comment]
To import the placement results of ISPD 2016 and ISPD 2017 into Vivado, you will need to contact AMD to request a patch.
